public class AccountDetails {

    private String accountName;
    public String rating {get; private set;}
    public String typex {private get;set;}
    public String partner {get;set;}
    public String phone;
    
        
    public void setName(String name){
        this.accountName=name;
    }
    
    public String getName(){
        return this.accountName;
    }
    
    public class AccountWrapper {

        private String accountName;
        private Integer noOfEmployees;
        
   }
   
    
}